# Generated by Django 4.2.2 on 2023-07-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_sqft_remove_listing_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
    ]
