bedroom_choices = {

  '0':'Bedsitter/Studio', 
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5
  }

price_choices = {
    '5000':'Ksh5,000',
    '10000':'Ksh10,000',
    '20000':'Ksh20,000',
    '30000':'Ksh30,000',
    '40000':'Ksh40,000',
    '50000':'Ksh50,000',
    '60000':'Ksh60,000',
    '70000':'Ksh70,000',
    '80000':'Ksh80,000',
    '90000':'Ksh90,000', 
    '100000':'Ksh100,000',
    '200000':'Ksh200,000',
}
county_choices = {

    "Baringo" : "BAR",
    "Bomet" : "BMT",
    "Bungoma" : "BGM",
    "Busia" : "BSA",
    "Elgeyo Marakwet" : "EGM",
    "Embu" : "EBU",
    "Garissa" : "GSA",
    "Homa Bay" : "HMA",
    "Isiolo" : "ISL",
    "Kajiado" : "KAJ",
    "Kakamega" : "KAK",
    "Kericho" : "KCO",
    "Kiambu" : "KBU",
    "Kilifi" : "KLF",
    "Kirinyaga" : "KIR",
    "Kisii" : "KSI",
    "Kisumu" : "KIS",
    "Kitui" : "KTU",
    "Kwale" : "KLE",
    "Laikipia" : "LKP",
    "Lamu" : "LAU",
    "Machakos" : "MCS",
    "Makueni" : "MUE",
    "Mandera" : "MDA",
    "Marsabit" : "MAR",
    "Meru" : "MRU",
    "Migori" : "MIG",
    "Mombasa" : "MBA",
    "Murang'a" : "MRA",
    "Nairobi" : "NBO",
    "Nakuru" : "NKU",
    "Nandi" : "NDI",
    "Narok" : "NRK",
    "Nyamira" : "NYI",
    "Nyandarua" : "NDR",
    "Nyeri" : "NER",
    "Samburu" : "SMB",
    "Siaya" : "SYA",
    "Taita Taveta" : "TVT",
    "Tana River" : "TAN",
    "Tharaka Nithi" : "TNT",
    "Trans Nzoia" : "TRN",
    "Turkana" : "TUR",
    "Uasin Gishu" : "USG",
    "Vihiga" : "VHG",
    "Wajir" : "WJR",
    "West Pokot" : "PKT"
}