bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'$100,000',
  '200000':'$200,000',
  '300000':'$300,000',
  '400000':'$400,000',
  '500000':'$500,000',
  '600000':'$600,000',
  '700000':'$700,000',
  '800000':'$800,000',
  '900000':'$900,000',
  '1000000':'$1M+',
}

state_choices = {

    "Baringo" : "BAR",
    "Bomet" : "BMT",
    "Bungoma" : "BGM",
    "Busia" : "BSA",
    "Elgeyo Marakwet" : "EGM",
    "Embu" : "EBU",
    "Garissa" : "GSA",
    "Homa Bay" : "HMA",
    "Isiolo" : "ISL",
    "Kajiado" : "KAJ",
    "Kakamega" : "KAK",
    "Kericho" : "KCO",
    "Kiambu" : "KBU",
    "Kilifi" : "KLF",
    "Kirinyaga" : "KIR",
    "Kisii" : "KSI",
    "Kisumu" : "KIS",
    "Kitui" : "KTU",
    "Kwale" : "KLE",
    "Laikipia" : "LKP",
    "Lamu" : "LAU",
    "Machakos" : "MCS",
    "Makueni" : "MUE",
    "Mandera" : "MDA",
    "Marsabit" : "MAR",
    "Meru" : "MRU",
    "Migori" : "MIG",
    "Mombasa" : "MBA",
    "Murang'a" : "MRA",
    "Nairobi" : "NBO",
    "Nakuru" : "NKU",
    "Nandi" : "NDI",
    "Narok" : "NRK",
    "Nyamira" : "NYI",
    "Nyandarua" : "NDR",
    "Nyeri" : "NER",
    "Samburu" : "SMB",
    "Siaya" : "SYA",
    "Taita Taveta" : "TVT",
    "Tana River" : "TAN",
    "Tharaka Nithi" : "TNT",
    "Trans Nzoia" : "TRN",
    "Turkana" : "TUR",
    "Uasin Gishu" : "USG",
    "Vihiga" : "VHG",
    "Wajir" : "WJR",
    "West Pokot" : "PKT"
}